### ISSUE TITLE
Write a dbload service

### ISSUE THREAD

**Issue by hancush** [datamade/committee-oversight#108]
There are currently four steps to populate the app database. String these together in a dbload service to minimize setup time. https://github.com/datamade/how-to/blob/master/docker/local-development.md#5-docker-composedb-opsyml-optional

**Comment by hancush** [comment]
What about a no-op `dbload` service that depends on two separate services, one based on the Postgres image to load the dump, and one based on the app image to apply the migrations and run the data loading commands? 

Helpful docs:
- https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on
- https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck

**Comment by hancush** [comment]
This looks like an even simpler approach: https://stackoverflow.com/a/54946350/7142170

**Comment by beamalsky** [comment]
I believe the second method you linked relies on postgres's [shell script initialization support](https://github.com/docker-library/postgres/blob/7e80419825e4bab4e749bc61334570ffc261ea5e/11/docker-entrypoint.sh#L147), which the image I'm using ([mdillon/postgis](https://hub.docker.com/r/mdillon/postgis/), for postgis) doesn't support.

Could you say more about what you mean by a no-op dbload service? Adding a `pg_restore` operation to the `dbload` file makes sense to me too, but this block: 

```
  dbload:
    container_name: committeeoversight-dbload
    image: committeeoversight:latest
    depends_on:
      - app
      - postgres
    volumes:
      - .:/app 
	  - ${PWD}/committeeoversight/local_settings.example.py:/app/committeeoversight/local_settings.py
    command: bash -c "pg_restore -C -j4 --no-owner -U postgres -d hearings /app/hearings.dump"
```

results in this error: `bash: pg_restore: command not found`

Do you understand why?

**Comment by hancush** [comment]
You're seeing that error because your `dbload` service is based off your application image, which doesn't include Postgres commands.

What I mean by a no-op `dbload` service is something like:

```yaml
dbload:
    ...
    depends on:
        postgres:
            condition: service_healthy
        app
    command: : 

postgres:
    command: pg_restore ...

app:
    command: bash -c "python manage.py migrate && python manage.py ..."
```

It will run the commands it depends on, then perform a no-op (`:`). Think of it a little like a Makefile!

I'm fairly certain you only need to define a command on the `postgres` and `app` services here, because docker-compose is smart enough to grab the other values from the `postgres` and `app` service definitions in your root docker-compose.yml file.

(I've never done this approach before, so I'm curious how/if it works!)
